language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURES=
    - FEATURES=acceleration,acceleration-src

script:
  - cargo test -vv --features=${FEATURES}

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
