language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURES=
    - FEATURES=acceleration,acceleration-src

script:
  - cargo test -vv --features=${FEATURES}
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      carbo bench --features=${FEATURES}
    fi

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
